# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64\x64ressbook.proto\x12\x10protobuf_example\"\xb3\x02\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x34\n\x06phones\x18\x04 \x03(\x0b\x32$.protobuf_example.Person.PhoneNumber\x1a`\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x41\n\x04type\x18\x02 \x01(\x0e\x32\".protobuf_example.Person.PhoneType:\x0fPHONE_TYPE_HOME\"h\n\tPhoneType\x12\x1a\n\x16PHONE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11PHONE_TYPE_MOBILE\x10\x01\x12\x13\n\x0fPHONE_TYPE_HOME\x10\x02\x12\x13\n\x0fPHONE_TYPE_WORK\x10\x03\"7\n\x0b\x41\x64\x64ressBook\x12(\n\x06people\x18\x01 \x03(\x0b\x32\x18.protobuf_example.Person')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addressbook_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PERSON']._serialized_start=40
  _globals['_PERSON']._serialized_end=347
  _globals['_PERSON_PHONENUMBER']._serialized_start=145
  _globals['_PERSON_PHONENUMBER']._serialized_end=241
  _globals['_PERSON_PHONETYPE']._serialized_start=243
  _globals['_PERSON_PHONETYPE']._serialized_end=347
  _globals['_ADDRESSBOOK']._serialized_start=349
  _globals['_ADDRESSBOOK']._serialized_end=404
# @@protoc_insertion_point(module_scope)
